name: Convert Model TF Converter

on:
  workflow_dispatch:

jobs:
  convert-tflite:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install onnx2tf==1.26.1
          pip install huggingface_hub
      - name: Convert
        run: |
          echo "test"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            convert_out/*.tflite
          if-no-files-found: error